[project]
name = "bogus"
version = "1.8"
description = "bogus"
readme = "README.md"
authors = [
    { name = "Kurt McKee", email = "contactme@kurtmckee.org" }
]
requires-python = ">=3.10"
license = "MIT"
dependencies = []

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
